linters:
    enable-all: true
    disable:
        - funlen
        - maligned

        # TODO: fix these
        - bodyclose
        - deadcode
        - dupl
        - errcheck
        - gas
        - gochecknoglobals
        - gochecknoinits
        - gocritic
        - gocyclo
        - gofmt
        - goimports
        - golint
        - lll
        - megacheck
        - varcheck

linters-settings:
    golint:
        min-confidence: 0.1
