builds:
    -
        main: ./cmd/banzai
        binary: banzai
        env:
            - CGO_ENABLED=0
        ldflags: "-s -w -X main.version={{ .Version }} -X main.commitHash={{ .ShortCommit }} -X main.buildDate={{ .Date }}"
        goos:
            - linux
            - darwin
            - windows
        goarch:
            - amd64

archive:
    name_template: "banzai_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
        -
            goos: windows
            format: zip

checksum:
    name_template: "banzai_checksums.txt"

changelog:
    skip: true

brew:
    github:
        owner: banzaicloud
        name: homebrew-tap
    folder: Formula
    homepage: https://banzaicloud.com/
    description: Command-line interface for Banzai Cloud Pipeline platform
    test: |
        system "#{bin}/banzai --version"
    dependencies:
        - kubectl
