[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/banzaicloud/pipeline"
  version = "0.6.4"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"
  version = "1.7.1"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "2.17.1"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "2.0.1"
