/*
 * Cluster Recommender.
 *
 * This project can be used to recommend instance type groups on different cloud providers consisting of regular and spot/preemptible instances. The main goal is to provide and continuously manage a cost-effective but still stable cluster layout that's built up from a diverse set of regular and spot instances.
 *
 * API version: 0.5.1
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telescopes

// VirtualMachine describes an instance type
type VirtualMachine struct {
	// Average price of the instance (differs from on demand price in case of spot or preemptible instances)
	AvgPrice float64 `json:"avgPrice,omitempty"`
	// Burst signals a burst type instance
	Burst bool `json:"burst,omitempty"`
	// Instance type category
	Category string `json:"category,omitempty"`
	// Number of CPUs in the instance type
	CpusPerVm float64 `json:"cpusPerVm,omitempty"`
	// CurrentGen the vm is of current generation
	CurrentGen bool `json:"currentGen,omitempty"`
	// Number of GPUs in the instance type
	GpusPerVm float64 `json:"gpusPerVm,omitempty"`
	// Available memory in the instance type (GB)
	MemPerVm float64 `json:"memPerVm,omitempty"`
	// NetworkPerf holds the network performance
	NetworkPerf string `json:"networkPerf,omitempty"`
	// NetworkPerfCat holds the network performance category
	NetworkPerfCategory string `json:"networkPerfCategory,omitempty"`
	// Regular price of the instance type
	OnDemandPrice float64 `json:"onDemandPrice,omitempty"`
	// Instance type
	Type string `json:"type,omitempty"`
	// Zones
	Zones []string `json:"zones,omitempty"`
}
