/*
 * Cluster Recommender.
 *
 * This project can be used to recommend instance type groups on different cloud providers consisting of regular and spot/preemptible instances. The main goal is to provide and continuously manage a cost-effective but still stable cluster layout that's built up from a diverse set of regular and spot instances.
 *
 * API version: 0.5.2
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telescopes
// ClusterRecommendationAccuracy ClusterRecommendationAccuracy encapsulates recommendation accuracy
type ClusterRecommendationAccuracy struct {
	// Number of recommended cpus
	Cpu float64 `json:"cpu,omitempty"`
	// Amount of master instance type prices in the recommended cluster
	MasterPrice float64 `json:"masterPrice,omitempty"`
	// The summarised amount of memory in the recommended cluster
	Memory float64 `json:"memory,omitempty"`
	// Number of recommended nodes
	Nodes int64 `json:"nodes,omitempty"`
	// Number of regular instance type in the recommended cluster
	RegularNodes int64 `json:"regularNodes,omitempty"`
	// Amount of regular instance type prices in the recommended cluster
	RegularPrice float64 `json:"regularPrice,omitempty"`
	// Number of spot instance type in the recommended cluster
	SpotNodes int64 `json:"spotNodes,omitempty"`
	// Amount of spot instance type prices in the recommended cluster
	SpotPrice float64 `json:"spotPrice,omitempty"`
	// Total price in the recommended cluster
	TotalPrice float64 `json:"totalPrice,omitempty"`
	// Amount of worker instance type prices in the recommended cluster
	WorkerPrice float64 `json:"workerPrice,omitempty"`
	// Availability zone in the recommendation
	Zone string `json:"zone,omitempty"`
}
