/*
 * Cluster Recommender.
 *
 * This project can be used to recommend instance type groups on different cloud providers consisting of regular and spot/preemptible instances. The main goal is to provide and continuously manage a cost-effective but still stable cluster layout that's built up from a diverse set of regular and spot instances.
 *
 * API version: 0.5.2
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telescopes
// NodePool NodePool represents a set of instances with a specific vm type
type NodePool struct {
	// Role in the cluster, eg. master or worker
	Role string `json:"role,omitempty"`
	// Recommended number of nodes in the node pool
	SumNodes int64 `json:"sumNodes,omitempty"`
	Vm VirtualMachine `json:"vm,omitempty"`
	// Specifies if the recommended node pool consists of regular or spot/preemptible instance types
	VmClass string `json:"vmClass,omitempty"`
}
