/*
 * Pipeline API
 *
 * Pipeline v0.3.0 swagger
 *
 * API version: pke-oidc-refactor
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipeline

type CreatePkeClusterKubernetes struct {
	Version string `json:"version"`
	Rbac bool `json:"rbac,omitempty"`
	Oidc CreatePkeClusterKubernetesOidc `json:"oidc,omitempty"`
	Cri CreatePkeClusterKubernetesCri `json:"cri,omitempty"`
	Network CreatePkeClusterKubernetesNetwork `json:"network,omitempty"`
}
