/*
 * Pipeline API
 *
 * Pipeline is a feature rich application platform, built for containers on top of Kubernetes to automate the DevOps experience, continuous application development and the lifecycle of deployments. 
 *
 * API version: latest
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipeline
// EksNodePoolVolumeNone We need this struct to be able to remove a volume in case of an update for example.
type EksNodePoolVolumeNone struct {
	// Type of the mounted volume's storage on the node instances of the node pool.
	Storage string `json:"storage"`
}
