name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    env:
      GO_VERSION: 1.14
      GOFLAGS: -mod=readonly

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3.2.1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go module dependencies
        id: cache-go-module-dependencies
        uses: actions/cache@v3.0.11
        with:
          path: ~/go/pkg/mod
          key: go-mod-cache-${{ runner.os }}-${{ env.GO_VERSION }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-mod-cache-${{ runner.os }}-${{ env.GO_VERSION }}
            go-mod-cache-${{ runner.os }}
            go-mod-cache

      - name: Download license information for dependencies
        env:
          GITHUB_TOKEN: ${{ github.token }} # Note: this is required for licensei auth in steps to avoid rate-limiting.
        run: make license-cache

      - name: List license information for dependencies
        env:
          GITHUB_TOKEN: ${{ github.token }} # Note: this is required for licensei auth in steps to avoid rate-limiting.
        run: ./bin/licensei list

      - name: Check dependency licenses
        env:
          GITHUB_TOKEN: ${{ github.token }} # Note: this is required for licensei auth in steps to avoid rate-limiting.
        run: make license-check

      - name: Build
        run: make build

      - name: Run linter
        run: make lint

      - name: Run tests
        run: GOARGS="-p=2" make test
